import { StyleSheet, Dimensions } from "react-native";

const { height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFF",
    },
    backgroundImage: {
        position: "absolute",
        width: "100%",
        height: height * 0.45,
    },
    containerPriceGenre: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        marginTop: height * 0.35,
    },
    content: {
        backgroundColor: "#FFF",
        borderTopRightRadius: 40,
        borderTopLeftRadius: 40,
        height: height,
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 600,
    },
    genre: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#FFF",
        marginBottom: 4,
    },
    price: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFF",
    },
    tagGenre: {
        backgroundColor: "rgba(250, 151, 185, 0.70)",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 20,
        padding: 15,
        gap: 10,
    },
    tagPrice: {
        backgroundColor: "rgba(81, 191, 55, 1)",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 30,
        padding: 15,
        gap: 10,
    },
    rowBetween: {
        flexDirection: "row",
        width: "100%",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 8,
        color: "#333",
    },
    ratingRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#FA97B9",
        padding: 10,
        gap: 5,
        borderRadius: 20,
    },
    rating: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFF",
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginTop: 15,
        marginBottom: 6,
        color: "#333",
    },
    description: {
        textAlign: "justify",
        fontSize: 15,
        color: "#555",
        lineHeight: 22,
    },
    itemContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        backgroundColor: "#F8F8F8",
        borderRadius: 12,
        padding: 12,
        marginBottom: 10,
        flexWrap: "wrap",
    },
    itemInfo: {
        flexDirection: "row",
        alignItems: "flex-start",
        flex: 1,
        gap: 10,
    },
    itemTextWrapper: {
        flex: 1,
        flexShrink: 1,
        flexWrap: "wrap",
        minWidth: 0,
    },
    itemName: {
        fontWeight: "bold",
        fontSize: 15,
        color: "#333",
        flexShrink: 1,
        flexWrap: "wrap",
        marginBottom: 2,
        width: "100%",
    },
    itemAuthor: {
        fontWeight: "500",
        fontSize: 13,
        color: "#777",
        marginBottom: 2,
    },
    itemIcon: {
        width: 40,
        height: 40,
        borderRadius: 8,
    },
    itemPrice: {
        fontSize: 13,
        color: "#777",
    },
    itemButtons: {
        flexDirection: "row",
        alignItems: "center",
    },
    quantityButton: {
        backgroundColor: "#FF1F6D",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    quantityText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    quantityValue: {
        marginHorizontal: 8,
        fontWeight: "bold",
        fontSize: 16,
    },
    addButton: {
        position: "absolute",
        bottom: 60,
        left: 20,
        right: 20,
        backgroundColor: "#FF1F6D",
        borderRadius: 14,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 14,
        gap: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    addButtonText: {
        color: "#FFF",
        fontSize: 16,
        fontWeight: "bold",
    },
    pickerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F8F8',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 5,
        marginTop: 8,
        marginBottom: 16,
    },
    picker: {
        flex: 1,
        color: '#333',
    },
});
