import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        alignItems: "center",
        justifyContent: "flex-end",
    },
    container: {
        backgroundColor: "#F7EEDD",
        width: '100%',
        paddingHorizontal: 20,
        paddingTop: 40,
        paddingBottom: 80,
        alignItems: 'center',
        justifyContent: "center",
        borderRadius: 40,
    },
    containerLogo: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    containerButton: {
        alignItems: 'center',
        justifyContent: "center",
        width: "100%",
        marginBottom: 20,
        gap: 10,
    },
    logo: {
        width: 350,
        height: 90,
        resizeMode: "contain",
    },
    title: {
        fontSize: 26,
        fontWeight: '700',
        color: "#FA97B9",
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: "#5C5C5C",
        textAlign: 'center',
        marginBottom: 30,
        width: '90%',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#FFF',
        borderRadius: 25,
        paddingHorizontal: 15,
        paddingVertical: 10,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#333',
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: "center",
        alignSelf: 'center',
        width: '100%',
        backgroundColor: "#FF1F6D",
        paddingVertical: 14,
        borderRadius: 25,
        marginVertical: 20,
    },
    buttonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: "#F7EEDD",
        marginRight: 10,
    },
    eyeButton: {
        position: 'absolute',
        right: 20,
    },
});
